export type AdvancedBIDomain =
  | "finance"
  | "retention"
  | "coaching_ops"
  | "client_health";

export type AdvancedBIReadiness = "supported" | "partial" | "blocked";

export interface AdvancedBIKPIContract {
  id: string;
  label: string;
  domain: AdvancedBIDomain;
  readiness: AdvancedBIReadiness;
  sourceTables: string[];
  grain: string;
  definition: string;
  caveat: string;
}

export const advancedBIKPIContract: AdvancedBIKPIContract[] = [
  {
    id: "gross_pack_sales",
    label: "Gross Pack Sales",
    domain: "finance",
    readiness: "supported",
    sourceTables: ["purchased_packs", "session_packs"],
    grain: "daily, coach, package",
    definition: "Sum package price at purchase time using purchased_packs.purchased_at.",
    caveat: "Uses pack purchases as sales truth; not yet reconciled to wallet ledger rows.",
  },
  {
    id: "pack_sales_count",
    label: "Pack Sales Count",
    domain: "finance",
    readiness: "supported",
    sourceTables: ["purchased_packs"],
    grain: "daily, coach, package",
    definition: "Count purchased packs.",
    caveat: "Refunded purchases need explicit restatement policy.",
  },
  {
    id: "average_order_value",
    label: "Average Order Value",
    domain: "finance",
    readiness: "supported",
    sourceTables: ["purchased_packs", "session_packs"],
    grain: "daily, weekly, monthly",
    definition: "Gross pack sales divided by pack sales count.",
    caveat: "Only valid while pack purchases remain the finance source for gross sales.",
  },
  {
    id: "refund_count",
    label: "Refund Count",
    domain: "finance",
    readiness: "partial",
    sourceTables: ["purchased_packs", "transactions"],
    grain: "daily, coach",
    definition: "Count refunded pack rows or refund ledger rows.",
    caveat: "Current schema lacks a single canonical refund event model.",
  },
  {
    id: "refund_amount",
    label: "Refund Amount",
    domain: "finance",
    readiness: "blocked",
    sourceTables: [],
    grain: "daily, coach, package",
    definition: "Sum refunded currency amount.",
    caveat: "No canonical refunded amount and refund timestamp tied to each sale.",
  },
  {
    id: "net_revenue",
    label: "Net Revenue",
    domain: "finance",
    readiness: "blocked",
    sourceTables: [],
    grain: "daily, coach, package",
    definition: "Gross revenue minus refunds and fees.",
    caveat: "Pack sales and wallet ledger do not reconcile into one finance model yet.",
  },
  {
    id: "platform_fee_revenue",
    label: "Platform Fee Revenue",
    domain: "finance",
    readiness: "partial",
    sourceTables: ["transactions", "admin_settings"],
    grain: "daily, coach",
    definition: "Sum explicit platform fee ledger rows.",
    caveat: "Config percentages are not enough for historical truth if ledger rows are missing.",
  },
  {
    id: "coach_payout_liability",
    label: "Coach Payout Liability",
    domain: "finance",
    readiness: "partial",
    sourceTables: ["wallets", "transactions"],
    grain: "current snapshot, daily",
    definition: "Outstanding coach balance and payout flow.",
    caveat: "Current balance is usable, but historical liability trend still needs a canonical ledger view.",
  },
  {
    id: "signups",
    label: "Signups",
    domain: "retention",
    readiness: "supported",
    sourceTables: ["user_profiles"],
    grain: "daily, weekly, monthly",
    definition: "Count new user profiles by created_at.",
    caveat: "None.",
  },
  {
    id: "activation_first_workout",
    label: "Activation to First Workout",
    domain: "retention",
    readiness: "supported",
    sourceTables: ["user_profiles", "workout_sessions"],
    grain: "signup cohort, daily",
    definition: "Users who complete a first workout after signup.",
    caveat: "Needs a final product decision on activation window length.",
  },
  {
    id: "activation_first_booking",
    label: "Activation to First Booking",
    domain: "retention",
    readiness: "supported",
    sourceTables: ["user_profiles", "bookings"],
    grain: "signup cohort, daily",
    definition: "Users who complete a first booking after signup.",
    caveat: "Needs a final product decision on activation window length.",
  },
  {
    id: "dau_wau_mau",
    label: "DAU / WAU / MAU",
    domain: "retention",
    readiness: "supported",
    sourceTables: ["workout_sessions"],
    grain: "rolling daily",
    definition: "Distinct workout users over 1, 7, and 30 days.",
    caveat: "Current BI v1 already uses this definition.",
  },
  {
    id: "cohort_retention",
    label: "Signup-to-Workout Cohort Retention",
    domain: "retention",
    readiness: "supported",
    sourceTables: ["user_profiles", "workout_sessions"],
    grain: "monthly cohort",
    definition: "Share of signup cohort active in later periods.",
    caveat: "Needs a materialized view for performance at BI scale.",
  },
  {
    id: "churn",
    label: "Churn",
    domain: "retention",
    readiness: "partial",
    sourceTables: ["user_profiles", "workout_sessions", "bookings", "purchased_packs"],
    grain: "monthly",
    definition: "Users active in a prior period but inactive in the current period.",
    caveat: "Still needs one agreed activity event set and churn window.",
  },
  {
    id: "reactivation",
    label: "Reactivation",
    domain: "retention",
    readiness: "partial",
    sourceTables: ["workout_sessions", "bookings"],
    grain: "monthly",
    definition: "Previously churned users becoming active again.",
    caveat: "Depends on the final churn definition.",
  },
  {
    id: "completed_bookings",
    label: "Completed Bookings",
    domain: "coaching_ops",
    readiness: "supported",
    sourceTables: ["bookings"],
    grain: "daily, coach",
    definition: "Count bookings marked completed.",
    caveat: "None.",
  },
  {
    id: "cancellation_rate",
    label: "Cancellation Rate",
    domain: "coaching_ops",
    readiness: "supported",
    sourceTables: ["bookings"],
    grain: "daily, coach",
    definition: "Cancelled bookings divided by total bookings.",
    caveat: "Needs final inclusion rules for reschedules.",
  },
  {
    id: "no_show_rate",
    label: "No-show Rate",
    domain: "coaching_ops",
    readiness: "supported",
    sourceTables: ["bookings"],
    grain: "daily, coach",
    definition: "No-show bookings divided by total bookings.",
    caveat: "None.",
  },
  {
    id: "active_clients_per_coach",
    label: "Active Clients per Coach",
    domain: "coaching_ops",
    readiness: "supported",
    sourceTables: ["purchased_packs", "bookings"],
    grain: "coach, current snapshot",
    definition: "Distinct active clients tied to each coach.",
    caveat: "Must decide whether bookings-only clients count as active.",
  },
  {
    id: "coach_review_score",
    label: "Coach Review Score",
    domain: "coaching_ops",
    readiness: "supported",
    sourceTables: ["coach_profiles"],
    grain: "coach",
    definition: "Current average rating and review count.",
    caveat: "None.",
  },
  {
    id: "coach_utilization",
    label: "Coach Utilization",
    domain: "coaching_ops",
    readiness: "partial",
    sourceTables: ["coach_availability", "bookings"],
    grain: "coach, week",
    definition: "Booked minutes divided by available minutes.",
    caveat: "Recurring availability exists, but time-off and exceptions are not modeled cleanly.",
  },
  {
    id: "coach_response_sla",
    label: "Coach Response SLA",
    domain: "coaching_ops",
    readiness: "partial",
    sourceTables: ["messages", "conversations", "coach_profiles"],
    grain: "coach, conversation",
    definition: "Time from client message to coach reply.",
    caveat: "Needs a canonical message-pairing rule.",
  },
  {
    id: "workout_inactivity_risk",
    label: "Workout Inactivity Risk",
    domain: "client_health",
    readiness: "supported",
    sourceTables: ["workout_sessions"],
    grain: "user, segment",
    definition: "Users with no recent workout activity over threshold windows.",
    caveat: "Thresholds still need product rules.",
  },
  {
    id: "workout_streak_consistency",
    label: "Workout Streak / Consistency",
    domain: "client_health",
    readiness: "supported",
    sourceTables: ["workout_sessions"],
    grain: "user, segment",
    definition: "Consecutive-day or weekly-consistency workout behavior.",
    caveat: "Exact streak formula must be frozen.",
  },
  {
    id: "nutrition_logging_adoption",
    label: "Nutrition Logging Adoption",
    domain: "client_health",
    readiness: "supported",
    sourceTables: ["meal_logs"],
    grain: "user, day, segment",
    definition: "Users who logged meals in a period.",
    caveat: "None.",
  },
  {
    id: "nutrition_goal_adherence",
    label: "Nutrition Goal Adherence",
    domain: "client_health",
    readiness: "partial",
    sourceTables: ["meal_logs", "food_items", "nutrition_goals"],
    grain: "user, day",
    definition: "Daily logged calories and macros versus daily goal.",
    caveat: "Source is good, but only for users who actively log nutrition.",
  },
  {
    id: "workout_adherence",
    label: "Workout Adherence",
    domain: "client_health",
    readiness: "blocked",
    sourceTables: [],
    grain: "user, coach",
    definition: "Completed assigned workouts divided by assigned workouts.",
    caveat: "No explicit assigned-vs-completed workout model exists today.",
  },
  {
    id: "program_completion",
    label: "Program Completion",
    domain: "client_health",
    readiness: "blocked",
    sourceTables: ["custom_programs"],
    grain: "user, coach",
    definition: "Completed programs divided by assigned programs.",
    caveat: "custom_programs has status, but no canonical completion progress model.",
  },
  {
    id: "body_progress_trend",
    label: "Body Progress Trend",
    domain: "client_health",
    readiness: "partial",
    sourceTables: ["body_measurements"],
    grain: "user, period",
    definition: "Change in body measurements over time.",
    caveat: "The table exists, but the on-device production pipeline is not shipped yet.",
  },
  {
    id: "health_sync_activity",
    label: "Health Sync Activity",
    domain: "client_health",
    readiness: "blocked",
    sourceTables: [],
    grain: "user, period",
    definition: "Steps, calories, or wearable-driven activity KPIs.",
    caveat: "The health_data feature is still pending.",
  },
  {
    id: "at_risk_client_score",
    label: "At-risk Client Score",
    domain: "client_health",
    readiness: "partial",
    sourceTables: ["workout_sessions", "meal_logs", "purchased_packs", "bookings"],
    grain: "user, coach",
    definition: "Composite risk score for inactivity, low adherence, or expiring coach relationship.",
    caveat: "Inputs exist for a basic score, but the scoring model is not defined yet.",
  },
];

export const advancedBIViewTargets = [
  {
    id: "bi_finance_daily",
    purpose: "Finance semantic layer for gross sales, fees, refunds, payouts, and liability.",
  },
  {
    id: "bi_user_lifecycle_daily",
    purpose: "Lifecycle semantic layer for signups, activation, active users, churn, and reactivation.",
  },
  {
    id: "bi_coach_ops_daily",
    purpose: "Coaching-ops semantic layer for bookings, cancellations, no-shows, active clients, and utilization inputs.",
  },
  {
    id: "bi_client_health_daily",
    purpose: "Client-health semantic layer for inactivity, streak inputs, nutrition adoption, adherence, and at-risk signals.",
  },
] as const;
